# layout -- 布局相关
# language: zh-CN

## menu 导航菜单显示
menu:
- page: home
  url: /
  icon: 
- page: 前端
  url: /zhengdingblog/categories/前端/
  icon: 
- page: 后端
  url: /zhengdingblog/categories/后端/
  icon: 
- page: 工具
  url: /zhengdingblog/categories/工具/
  icon: 
- page: 资源
  url: /zhengdingblog/categories/资源/
  icon: 

## favicon 
favicon: /favicon.ico

## Feed 
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
- notification
- social
- category
- archive
- tagcloud
- friends

## 网站公告设置
notification: |-
            <p>欢迎进入我的博客~ <br/>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/shenliyang
 - name: 邮箱
   icon: envelope-o
   href: mailto:snippet@91h5.cc
 - name: 联系QQ
   icon: qq
   href: /
 - name: 微博
   icon: weibo
   href: /
 - name: QQ群
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:
  - 个人博客: http://ding-data.gitee.io/zhengdingblog/



# 主题自定义个性化配置

## 网站宣传语
branding: 

## 懒加载图片占位符
placeholder: ./img/loading.gif

## 缩略图自定义随机图片
defaultImgs:
  - 

## 截取文章首页描述字数
excerptLength: 120

## 当无分类时显示文字，默认为'无'
noCategoryText: '无'

## 代码高亮配置
highlightTheme: default

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 添加版权保护 
##archiveCopyright:
##  enable: true
 ## tip: '商业转载请联系作者获得授权,非商业转载请注明出处 © Snippet'

## 版权声明文字，支持html/text，但不要使用<li>标签
##cc: |-
##      <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/" target="_blank">
 ##     知识共享署名-非商业性使用-禁止演绎 3.0 未本地化版本许可协议（CC BY-NC-ND 3.0）
 ##     </a>

## 过低版本的浏览器提醒文字
outdated_browser_text: '你使用的浏览器版本过低，为了你更好的阅读体验，请更新浏览器的版本或者使用其他现代浏览器，比如Chrome、Firefox、Safari等。'


## 主题评论
### gitment
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
  perPage: 10


### 友言评论
uyan:
  enable: true
  uyan_id: 1966422


## 网站访问统计

### 网盟CNZZ统计
cnzz_anaylytics: 1263868967

### 百度统计
baidu_anaylytics: 

### 谷歌统计
google_anaylytics: 

### 百度文章推送
baidu_push:

#网站主题配置
since: 2017
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.1.0
